"""remove unique constraint from ai_evaluations

Revision ID: 06124bf01cc0
Revises: 1d1fe782b51e
Create Date: 2026-06-06 19:33:45.910880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06124bf01cc0'
down_revision: Union[str, Sequence[str], None] = '1d1fe782b51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
