"""updated jd model schema

Revision ID: 5ba60afbebad
Revises: 1d1fe782b51e
Create Date: 2026-06-03 23:29:11.357540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ba60afbebad'
down_revision: Union[str, Sequence[str], None] = '1d1fe782b51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('job_code', sa.String(length=20), nullable=True))
    op.add_column('job_descriptions', sa.Column('keywords', sa.Text(), nullable=True))
    op.alter_column('job_descriptions', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('job_descriptions', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('job_descriptions', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('job_descriptions', 'requirements',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('job_descriptions', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'OPEN', 'CLOSED', name='job_status'),
               nullable=False)
    op.create_index(op.f('ix_job_descriptions_job_code'), 'job_descriptions', ['job_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_descriptions_job_code'), table_name='job_descriptions')
    op.alter_column('job_descriptions', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'OPEN', 'CLOSED', name='job_status'),
               nullable=True)
    op.alter_column('job_descriptions', 'requirements',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_descriptions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_descriptions', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('job_descriptions', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('job_descriptions', 'keywords')
    op.drop_column('job_descriptions', 'job_code')
    # ### end Alembic commands ###
